"""
GenJAX Curvefit Case Study - Simplified Main Entry Point

Supports three modes:
- quick: Fast demonstration with basic visualizations
- full: Complete analysis with all visualizations
- benchmark: Framework comparison (IS 1000 vs HMC methods)
"""

import argparse


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="GenJAX Curvefit Case Study - Bayesian Sine Wave Parameter Estimation"
    )

    parser.add_argument(
        "mode",
        choices=["paper"],
        nargs="?",
        default="paper",
        help="Analysis mode: paper (generate only paper figures)",
    )

    # Analysis parameters
    parser.add_argument(
        "--n-points", type=int, default=10, help="Number of data points (default: 10)"
    )
    parser.add_argument(
        "--n-samples-is",
        type=int,
        default=1000,
        help="Number of importance sampling particles (default: 1000)",
    )
    parser.add_argument(
        "--n-samples-hmc",
        type=int,
        default=1000,
        help="Number of HMC samples (default: 1000)",
    )
    parser.add_argument(
        "--n-warmup",
        type=int,
        default=500,
        help="Number of HMC warmup samples (default: 500)",
    )
    parser.add_argument(
        "--timing-repeats",
        type=int,
        default=20,
        help="Timing repetitions (default: 20)",
    )
    parser.add_argument(
        "--seed", type=int, default=42, help="Random seed (default: 42)"
    )

    # Outlier model parameters
    parser.add_argument(
        "--outlier-rate",
        type=float,
        default=0.2,
        help="Prior outlier probability (default: 0.2)",
    )
    parser.add_argument(
        "--outlier-mean",
        type=float,
        default=0.0,
        help="Outlier distribution mean (default: 0.0)",
    )
    parser.add_argument(
        "--outlier-std",
        type=float,
        default=5.0,
        help="Outlier distribution std dev (default: 5.0)",
    )
    parser.add_argument(
        "--outlier-comprehensive",
        action="store_true",
        help="Run comprehensive outlier analysis with all figures",
    )

    # Scaling benchmark controls
    parser.add_argument(
        "--scaling-trials",
        type=int,
        default=5,
        help="Trials per particle count in the scaling benchmark (default: 5)",
    )
    parser.add_argument(
        "--scaling-max-large-trials",
        type=int,
        default=2,
        help="Maximum trials to run for particle counts above 100k (default: 2)",
    )
    parser.add_argument(
        "--scaling-max-samples",
        type=int,
        help="Upper bound on particle counts (filters the default grid)",
    )
    parser.add_argument(
        "--scaling-particle-counts",
        type=str,
        help="Comma-separated list overriding the default particle counts",
    )
    parser.add_argument(
        "--scaling-extended-timing",
        action="store_true",
        help="Enable extended timing sweeps for the scaling figure",
    )

    return parser.parse_args()


# All old modes removed - keeping only paper mode


def _parse_particle_counts_arg(arg: str | None) -> list[int] | None:
    if not arg:
        return None
    counts = []
    for chunk in arg.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        try:
            counts.append(int(chunk))
        except ValueError as exc:
            raise ValueError(
                f"Invalid integer '{chunk}' in --scaling-particle-counts"
            ) from exc
    return counts or None


def run_paper_mode(args):
    """Generate only the figures used in the POPL paper."""
    from examples.curvefit.figs import (
        save_multiple_multipoint_traces_with_density,
        save_single_multipoint_trace_with_density,
        save_inference_scaling_viz,
        save_posterior_scaling_plots,
        save_outlier_detection_comparison,
    )

    print("=== Paper Mode: POPL Figure Generation ===")

    save_multiple_multipoint_traces_with_density()
    save_single_multipoint_trace_with_density()
    save_inference_scaling_viz(
        n_trials=args.scaling_trials,
        particle_counts=_parse_particle_counts_arg(args.scaling_particle_counts),
        max_large_trials=args.scaling_max_large_trials,
        max_samples=args.scaling_max_samples,
        extended_timing=args.scaling_extended_timing,
    )
    save_posterior_scaling_plots()
    save_outlier_detection_comparison()

    print("\nPaper mode complete!")
    print("Generated figures:")
    print("  - curvefit_prior_multipoint_traces_density.pdf")
    print("  - curvefit_single_multipoint_trace_density.pdf")
    print("  - curvefit_scaling_performance.pdf")
    print("  - curvefit_posterior_scaling_combined.pdf")
    print("  - curvefit_outlier_detection_comparison.pdf")
    print(
        "\nNote: curvefit_vectorization_illustration.pdf is a static diagram (not generated by code)"
    )


def main():
    """Main entry point."""
    args = parse_args()

    print("\nGenJAX Curvefit Case Study")
    print("Mode: paper (artifact submission)")

    run_paper_mode(args)

    print("\nDone!")


if __name__ == "__main__":
    main()
